version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: clinical_backend
    ports:
      - "8000:8000"
    volumes:
      - ./qdrant_db:/app/qdrant_db # Mounts your local DB into the container
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: clinical_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_HOST=backend # Tells python to look for the container named 'backend'
    depends_on:
      - backend # Waits for backend to start first